version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
  pre_build:
    commands:
      - corepack prepare
      - pnpm install --frozen-lockfile
  build:
    commands:
      - pnpm build
